FROM golang:1.18

RUN go install github.com/jstemmer/go-junit-report@latest

ENV CGO_ENABLED=0

WORKDIR /go/src/github.com/cyverse-de/QMS
COPY . .
RUN go build --trimpath -o cmd/fix-usernames ./cmd/fix-usernames

FROM debian:stable-slim

COPY --from=0 /go/src/github.com/cyverse-de/QMS/cmd/fix-usernames/fix-usernames /bin

ENTRYPOINT ["fix-usernames"]

EXPOSE 8080
