apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: qms
build:
  artifacts:
  - image: harbor.cyverse.org/de/qms
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/qms.yml
