apiVersion: apps/v1
kind: Deployment
metadata:
  name: qms
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: qms
  template:
    metadata:
      labels:
        de-app: qms
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: de-app
                    operator: In
                    values:
                      - qms
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
      containers:
        - name: qms
          image: harbor.cyverse.org/de/qms
          env:
            - name: QMS_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: QMS_DATABASE_URI
            - name: QMS_REINIT_DB
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: QMS_REINIT_DB
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_TRACES_EXPORTER
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
          resources:
            requests:
              cpu: "1m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: timezone
              mountPath: /etc/timezone
              subPath: timezone
          ports:
            - name: listen-port
              containerPort: 9000
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: qms
spec:
  selector:
    de-app: qms
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
